# Generated by Django 5.1.2 on 2024-11-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_sale_sale_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
