# Generated by Django 5.1.2 on 2024-11-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_sale_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesreceipt",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
