# Generated by Django 5.1.2 on 2024-11-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
