version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --chdir src system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - CSRF_TRUSTED_ORIGINS
      - B2_ACCESS_KEY_ID
      - B2_SECRET_ACCESS_KEY
      - B2_STORAGE_BUCKET_NAME
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_PORT
      - EMAIL_USE_TLS
      - DEFAULT_FROM_EMAIL
