version: '3.8'

services:
  web:
    build: .
    command: gunicorn src.system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=src.system.settings
      - DATABASE_URL=postgres://username:password@db:5432/database_name
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

networks:
  default:
    external:
      name: your_external_network
