# Generated by Django 5.1.2 on 2024-11-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_inventory_max_stock_alter_inventory_min_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="max_stock",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="min_stock",
            field=models.IntegerField(blank=True),
        ),
    ]
