# Generated by Django 5.1.2 on 2024-11-13 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_uuid",
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
    ]
