# Generated by Django 5.1.2 on 2024-11-14 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_delivery_staff_deliveryreceipt_receipt_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="delivery_uuid",
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_uuid",
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="deliverydetail",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=1, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="salesdetail",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=1, max_digits=10
            ),
        ),
    ]
