# Generated by Django 5.1.2 on 2024-11-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="depth",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="refriderated",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=100, null=True
            ),
        ),
    ]
