# Generated by Django 5.1.2 on 2024-11-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_cost_price_alter_product_depth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="max_stock",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="min_stock",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
